Update readme and dependencies to prepare for publishing
CMSgov/price-transparency-guide-validator pull request #39
Opened 2022-03-22 17:16 UTC by mint-thompson

Installation instructions now use npm instead of local files.
This allows the wrapper to be run from any directory if installed globally.

This should be all the things that need to be cleaned up for an initial release on npm.

2022-03-22 19:40 UTC, shaselton-usds commented
@mint-thompson I wasn't able to pull the npm package from the `npm install -g cms-mrf-validator` command. I got a 404 with the following message

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/cms-mrf-validator - Not found
npm ERR! 404
npm ERR! 404  'cms-mrf-validator@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

2022-03-22 19:40 UTC, shaselton-usds commented
Might this be an opportunity to update the version to 1.0 or were we waiting on something else to get us to that point?

2022-03-22 19:44 UTC, shaselton-usds requested changes
Need to update the NPM repo with the package to pull down.

2022-03-23 13:00 UTC, mint-thompson commented
@shaselton-usds the package should now be actually available on NPM: https://www.npmjs.com/package/cms-mrf-validator

2022-03-23 19:29 UTC, shaselton-usds approved these changes

2022-03-23 19:29 UTC, shaselton-usds commented
Great, was able to run locally without issue. Thanks!

2022-03-25 16:24 UTC, merged